### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by shahramn** [erget/libaec#2]
Is the library thread-safe?

**Comment by erget** [comment]
Puh, it's been over half a decade since I looked at this... As we say in Germany, here I am überfragt ;) Perhaps @MathisRosenhauer can shed more insight?

**Comment by MathisRosenhauer** [comment]
Good to hear from you again, Daniel. The lib itself should be thread-safe. If you are using it with hdf5 or ecCodes, you have to make sure that those libs are compiled with the right options for thread-safety.

**Comment by shahramn** [comment]
Thank you. Have you run tests with multiple threads (decoding and encoding) using say the clang thread-sanitizer?

**Comment by MathisRosenhauer** [comment]
No, I haven't yet. I'll look into this when I find time to work on the lib again. In the meantime feel free to submit a PR. Preferably at my repo MathisRosenhauer/libaec

**Comment by shahramn** [comment]
I just ran some tests in ecCodes (built with POSIX threads) encoding fields in parallel with CCSDS packing(8 and 16 threads). Using clang thread-sanitizer. So far have not come across any errors (data races etc).
