### ISSUE TITLE
szip compatibility

### ISSUE THREAD

**Issue by pcasenove** [erget/libaec#3]
Hi,
We are currently using SZIP and after a conda update, libaec has been installed.
In https://github.com/erget/libaec/blob/cmake-install-instructions/README.SZIP, we can see:
Libaec includes a free drop-in replacement for the SZIP
library[1]. Just replace SZIP's shared library libsz.so* with
libaec.so* and libsz.so* from libaec 

However, our compilation, which took libaec by mistake, crashes with the following error:
.../src/lib/Uncompressor.cpp:216:30: error: 'szip_uncompress_memory' was not declared in this scope
  216 |     decompressedDataLength = szip_uncompress_memory(options_mask, bitsPerPixel, pixelsPerBlock, scanlineLength,
      |                              ^~~~~~~~~~~~~~~~~~~~~~

Indeed, szip_uncompress_memory doesn't appear anymore while it was [here](https://github.com/erdc/szip/blob/master/src/sz_api.c#L55) in the original SZIP.

Is it a mistake on your side or do you mean that the functionnalities are equivalent, while the API still differ between the two packages?

Thanks,

**Comment by erget** [comment]
Thanks for reporting - in fact I've updated the repo in fd854a2fdcc6bda757ff59b517eb42292484043d to note that it's not maintained here - apologies for the confusion. Please [contact upstream](https://gitlab.dkrz.de/k202009/libaec/-/issues) for issues.
